### PR TITLE
Fix avatar physical proxy.

### PR DESCRIPTION
**Pull request by Hoikas**
This fixes the avatar physical proxy. The capsule generation code was derived from the same in libcinder. If you would like to contribute a better capsule generator, be my guest :smile:
Screenshot 2021-04-05 17 13 09

### CODE REVIEW

**Comment by Hoikas** [comment]
`/home/runner/work/Plasma/Plasma/Sources/Plasma/PubUtilLib/plDrawable/plDrawableGenerator.cpp:411:27: error: ‘sinf’ is not a member of ‘std’; did you mean ‘sinh’?`

Anybody know what GCC is smoking?

**Comment by branan** [comment]
> `/home/runner/work/Plasma/Plasma/Sources/Plasma/PubUtilLib/plDrawable/plDrawableGenerator.cpp:411:27: error: ‘sinf’ is not a member of ‘std’; did you mean ‘sinh’?`
> 
> Anybody know what GCC is smoking?

Suffixed `sin_` functions were only added in c++11. Before that you just had to trust your operator overloading on `sin`

**Comment by branan** [comment]
You can also include the C math.h and use the un-namespaced sinf

**Comment by Hoikas** [comment]
`CMAKE_CXX_STANDARD` is 17 😕

**Comment by branan** [comment]
In that case, I'm with you on the original question. Even if something got implicitly promoted or converted you should have gotten a type error, not a missing function? 🤔

**Comment by zrax** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79700

**Review by Deledrius — APPROVED** [review]

**Pull request merged**
