### PR TITLE
Merge moul scripts

### PR DESCRIPTION
**Pull request by zrax**
This merges [moul-scripts](https://github.com/H-uru/moul-scripts) into Plasma, making the latter a Plasma "monorepo"

To be merged upstream before merging:
* [X] H-uru/moul-scripts#118
* [x] H-uru/moul-scripts#119
* [X] H-uru/moul-scripts#121

To be migrated after merging:
* H-uru/moul-scripts#2
* H-uru/moul-scripts#59
* H-uru/moul-scripts#114
* H-uru/moul-scripts#124
* H-uru/moul-scripts#77
* H-uru/moul-scripts#111 (integrate into #596?)
* H-uru/moul-scripts#122

### CODE REVIEW

**Comment by Deledrius** [comment]
Thanks for pulling these all over with history intact, @zrax!

This is a pretty big change.  Maybe we should go over the pros/cons of doing this for reference?

**Comment by Hoikas** [comment]
My thought process was how interrelated the Python API is with the engine itself - we wind up having several situations where we have to make changes in two repositories. The downside is that we have more data-dependent things in the engine repository... but were we ever going to make the engine truly data-independent?

**Comment by Hoikas** [comment]
Looking at the progress we need to make to upgrade to Python 3... I think it would be nice to have this PR merged before work begins on Python 3. In terms of the scripts side, H-uru/moul-scripts#118 and H-uru/moul-scripts#121 are ready to be merged. H-uru/moul-scripts#119 needs to be reviewed, but it is basically a requirement before any useful work can begin on Py3.

I think those three PRs should be merged in the legacy moul-scripts repository and this PR should be updated to reflect those changes. Any other PRs or future work should proceed on top of this PR. Thoughts?

**Comment by zrax** [comment]
I'm fine with rebasing this after those PRs are merged upstream

**Comment by Hoikas** [comment]
All prerequisite PRs have been merged!

**Comment by zrax** [comment]
Rebase applied!

**Comment by Hoikas** [comment]
Per @aqua-uru in IRC:
> maybe remove 'moul-scripts' from the README in merge-moul-scripts?

**Comment by Hoikas** [comment]
💥 💥 💥

**Pull request merged**
