### PR TITLE
Fix some moar Coverity

### PR DESCRIPTION
**Pull request by Hoikas**
Fixes some issues pointed out by Coverity. The biggest change here is that the Max plugin will now produce lightmaps correctly :smile:.

### CODE REVIEW

**Comment by zrax** [comment]
:+1: 
I wonder if older versions of MSVC handled `const` differently in virtual function overrides...

**Comment by dpogue** [comment]
:+1:

**Comment by Hoikas** [comment]
That's what I was thinking, @zrax.

**Comment by branan** [comment]
I would not at all be surprised if old versions of MSVC did not correctly deal with `const` virtual function overrides

**Comment by branan** [comment]
Did you double-check that the constness is the same across all versions of the Max SDK? I also would not be surprised if we need to #ifdef this...

**Comment by Hoikas** [comment]
Zrax uses the 2012 SDK on covering, and I saw a mismatch on max 7,which was
good enough for me

**Pull request merged**
