### PR TITLE
Download and install the PhysX SDK from archive.org

### PR DESCRIPTION
**Pull request by zrax**
This removes the final dependency on the non-redist devlibs for CI.

### CODE REVIEW

**Comment by Hoikas** [comment]
O.o it's exploding on OpenAL...

**Comment by Hoikas** [comment]
This is failing because the `vcpkg install [...]` command does not include the `--recurse` option, apparently 🙄

**Comment by zrax** [comment]
I'm not too excited about fixing it with #690 on the horizon ;)

**Comment by zrax** [comment]
Closing this in favor of #690.

**Pull request closed without merging**
