### PR TITLE
Update xLinkingBookDefs.py for Elonin

### PR DESCRIPTION
**Pull request by DoobesURU**
Adds Book definitions for the Elonin cavern location.

### CODE REVIEW

**Comment by Hoikas** [comment]
There is no accepted Age called "Elonin" FWIW.

**Comment by DoobesURU** [comment]
> There is no accepted Age called "Elonin" FWIW.

Yeah, I still need to chat with Dulcamara and ametist on how they want to handle that. Should hopefully be cleared up soon.

**Comment by DoobesURU** [comment]
Elonin PR: #1136 For some reason, the script review is coughing up an error.

**Comment by DoobesURU** [comment]
Closing due to carrying over these changes to #1136 per @Hoikas ' suggestion.

**Pull request closed without merging**
