### PR TITLE
Port hsThread to a std::thread-based implementation

### PR DESCRIPTION
**Pull request by zrax**
hsThread now becomes a wrapper around a std::thread, while maintaining the comfortable class-based API.

This does not include the port of AsyncCore to hsThread/std::thread, as that part has many more conflicts with #412

### CODE REVIEW

**Comment by Hoikas** [comment]
This PR seems to have introduced a crash when the patcher thread is shutting down.

**Comment by Hoikas** [comment]
```
 	msvcr120.dll!abort() Line 88	C
 	msvcr120.dll!terminate() Line 96	C++
 	msvcr120.dll!_CallSettingFrame(unsigned long funclet, unsigned long pRN, unsigned long dwInCode) Line 64	Unknown
 	msvcr120.dll!__FrameUnwindToState(EHRegistrationNode * pRN, void * pDC, const _s_FuncInfo * pFuncInfo, int targetState) Line 1086	C++
 	msvcr120.dll!__InternalCxxFrameHandler(EHExceptionRecord * pExcept, EHRegistrationNode * pRN, _CONTEXT * pContext, void * pDC, const _s_FuncInfo * pFuncInfo, int CatchDepth, EHRegistrationNode * pMarkerRN, unsigned char recursive) Line 394	C++
 	msvcr120.dll!__CxxFrameHandler(EHExceptionRecord * pExcept, EHRegistrationNode * pRN, void * pContext, void * pDC) Line 301	C++
 	ntdll.dll!ExecuteHandler2@20()	Unknown
 	ntdll.dll!ExecuteHandler@20()	Unknown
 	msvcr120.dll!_UnwindNestedFrames(EHRegistrationNode * pRN, EHExceptionRecord * pExcept) Line 231	C++
 	msvcr120.dll!CatchIt(EHExceptionRecord * pExcept, EHRegistrationNode * pRN, _CONTEXT * pContext, void * pDC, const _s_FuncInfo * pFuncInfo, const _s_HandlerType * pCatch, const _s_CatchableType * pConv, const _s_TryBlockMapEntry * pEntry, int CatchDepth, EHRegistrationNode * pMarkerRN, unsigned char IsRethrow)	C++
 	msvcr120.dll!FindHandler(EHExceptionRecord * pExcept, EHRegistrationNode * pRN, _CONTEXT * pContext, void * pDC, const _s_FuncInfo * pFuncInfo, unsigned char recursive, int CatchDepth, EHRegistrationNode * pMarkerRN) Line 689	C++
 	msvcr120.dll!__InternalCxxFrameHandler(EHExceptionRecord * pExcept, EHRegistrationNode * pRN, _CONTEXT * pContext, void * pDC, const _s_FuncInfo * pFuncInfo, int CatchDepth, EHRegistrationNode * pMarkerRN, unsigned char recursive) Line 439	C++
 	msvcr120.dll!__CxxFrameHandler(EHExceptionRecord * pExcept, EHRegistrationNode * pRN, void * pContext, void * pDC) Line 301	C++
 	ntdll.dll!ExecuteHandler2@20()	Unknown
 	ntdll.dll!ExecuteHandler@20()	Unknown
 	ntdll.dll!_KiUserExceptionDispatcher@8()	Unknown
 	KernelBase.dll!_RaiseException@16()	Unknown
 	msvcr120.dll!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 152	C++
 	msvcp120.dll!std::_Throw_Cpp_error(int code) Line 45	C++
 	plClient.exe!std::thread::join() Line 213	C++
>	plClient.exe!pfPatcherWorker::~pfPatcherWorker() Line 359	C++
 	plClient.exe!pfPatcherWorker::`scalar deleting destructor'(unsigned int)	C++
 	plClient.exe!pfPatcher::~pfPatcher() Line 572	C++
 	plClient.exe!pfPatcherWorker::OnQuit() Line 364	C++
 	msvcp120.dll!_Call_func(void * _Data) Line 28	C++
 	msvcr120.dll!_callthreadstartex() Line 376	C
 	msvcr120.dll!_threadstartex(void * ptd) Line 354	C
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown
```

**Comment by Hoikas** [comment]
The aforementioned crash is still occurring.

`_Throw_Cpp_error(_RESOURCE_DEADLOCK_WOULD_OCCUR);`

**Comment by zrax** [comment]
I've pushed an (untested) fix to let the `pfPatcher` thread run detached, so it should be able to delete itself without crashing.

**Comment by Hoikas** [comment]
Works 100%

**Pull request merged**
