### PR TITLE
Create folder hierarchy in IDE project views

### PR DESCRIPTION
**Pull request by dpogue**
Makes a folder hierarchy in IDEs that roughly matches the folder layout of the Plasma projects.

VS 2022 project Solution Explorer:
Visual Studio 2022 Project

VS 2022 open folder CMake Targets:
Visual Studio 2022 CMake Folder View

Xcode project file sidebar:
Xcode Project

### CODE REVIEW

**Review by Hoikas — COMMENTED** [review]
Does `cmake/PlasmaTargets.cmake` use the wrong line endings or something? The diff is basically the whole file, which makes it very hard to read.

**Comment by dpogue** [comment]
> Does `cmake/PlasmaTargets.cmake` use the wrong line endings or something?

I think the line endings might have been wrong on master, and it got swapped to LF here 😕

**Comment by Hoikas** [comment]
Can we defer the line ending conversion or another PR?

**Comment by dpogue** [comment]
Should be better now

**Review by Hoikas — APPROVED** [review]

**Review by Deledrius — APPROVED** [review]

**Pull request merged**
