### PR TITLE
Fix build for Appveyor environment.

### PR DESCRIPTION
**Pull request by Deledrius**
This is a collection of fixes to make building under Appveyor's environment possible/easier, and some general updates to the library usages.

### CODE REVIEW

**Comment by Deledrius** [comment]
Note: This does *not* include the appveyor.yaml, as I had intended, because there are a few aspects that need discussion.  I opened this PR to hash that out with the team, after which I can add it as a final commit if desired.

The current configuration is fully functional and builds the entire client, all the tools, and the `resource.dat`, only currently excluding the Max plugin.  In order to accomplish building the client, I supply a zipped archive containing the minimal necessary portions of the PhysX and OpenAL SDKs.  What are our options for doing this as a regular build?  

Connected to the above question is the Max SDKs: is it possible to use them in our public build environment?

**Comment by zrax** [comment]
I have no idea about the proprietary SDKs...  In fact I've been avoiding the Plasma repo for now for exactly that reason.  As for the other libs, I'm working on https://github.com/H-uru/Plasma/PlasmaPrefix to try to make it easier to build those and keep them up-to-date for our supported compilers.

**Comment by Hoikas** [comment]
Is it possible to run the installers for PhysX and OpenAL on AppVeyor?

**Comment by zrax** [comment]
As long as it can be run without user interaction, yes, it should be possible.  I was briefly running the nasm installer like that, and it worked as expected.

**Comment by Deledrius** [comment]
I wasn't able to get them to run that way, unfortunately.  It might be possible, but I did not find a way to do so.  That was the first thing I tried.  They both use weird installers, IIRC.

**Comment by Hoikas** [comment]
That seems like a good compromise solution to me :smile:

**Comment by Deledrius** [comment]
If so, do we also want to build the Max plugin that way too?  We could theoretically build each supported version this way.

**Pull request merged**
