### PR TITLE
String theory preparation

### PR DESCRIPTION
**Pull request by zrax**
This prepares for an eventual String Theory port by removing the deprecated parts of plString and replacing them with ST-compatible equivalents.  The actual ST port will be larger and more mind-numbing, so it would be good to ensure this part works properly first.

### CODE REVIEW

**Comment by dpogue** [comment]
This probably also resolves #480.

**Comment by Michellacoste** [comment]
Is this going to solve the display problem of special foreign language characters (such as é, è, â, etc ...)?

**Comment by zrax** [comment]
Issues with display of non-ASCII characters should be in the font rendering code... This PR shouldn't affect the font rendering

**Comment by Deledrius** [comment]
Finally had some time to read through this monster.  I don't see anything out of order here. :+1:

**Pull request merged**
