### PR TITLE
Restore support for GameMgr-based marker games.

### PR DESCRIPTION
**Pull request by Hoikas**
This re-adds support for the game manager to our codebase in a way that allows the client to use the "new" style marker games, garden doors, etc. on servers that do not support the game manager and falls back to the game managers on servers that do (eg MOULa). In this way, our client can be more safely used by individuals who do not understand the implications of our changes.

This pull request only addresses the core game manager functionality and marker games. Per discussion in IRC, it seems the desired approach is to perform one pull request per game type.

Depends on #1179, so go review that.

### CODE REVIEW

**Comment by Hoikas** [comment]
This PR is now closer to being review-ready. The Python stubs are still missing docstrings, however, and there probably needs to be some thought about how to document the `pfGameHandler` class's Python interface.

**Comment by Hoikas** [comment]
Python docstrings added; therefore, we are ready.

**Comment by Hoikas** [comment]
This needs to be rebased onto master in light of #1179 being merged.

**Comment by Hoikas** [comment]
Rebased onto master.

**Comment by DamnBriggsy** [comment]
With the understanding that the garden age door game functionality is not yet complete here, this is how the H'uru and MOULa clients behave when both are present:

- The H'uru client sees the numbers appear on the door when the MOULa client presses the cloths. Nobody sees them when the H'uru client press the cloth. The cloth itself behaves normally (avatar animates, cloth lights up, plays SFX).
- If the H'uru client clicks the door, nothing appears to happen from either perspective, and the H'uru client can't click it again for the amount of time it would take to complete its cycle.
- The H'uru client doesn't see lights when the MOULa client clicks the door, but it will silently start to rotate through its usual sequence.
- As the code is entered, the SFX for successful entries is heard but no lights are seen by MOULa or H'uru clients. The H'uru client and the MOULa client both see a flash on all lights when the first number is entered, but none after that. On subsequent attempts, there is no flash.
- It's likely the door can be solved in this state by MOULa clients, but the lights around the rim are not shown to anyone. MOULa clients that link away and back to the age will experience the proper door game with all lights and sounds.

**Comment by DamnBriggsy** [comment]
Testing marker games between clients today. It works well, with one exception in **bold**:

- H'uru client can create, edit, and play a marker quest.
- H'uru client can create custom text for markers, and that custom text will appear when those markers are collected.
- H'uru client can send a marker quest to a MOULa client and it will be playable
- **Any marker quest sent from the H'uru client will have all custom text erased and replaced with the default marker text immediately upon sending. Both clients will then see the default text**
- MOULa client can create, edit, and send a marker quest to the H'uru client and it will be playable
- Marker quests with custom text created on the MOULa client and sent via KImail will retain the custom text

**Comment by DamnBriggsy** [comment]
It was requested that linking to another age while playing a marker game be tested. This is what happens:

**H'uru client:**
- Marker game created in Relto, one marker assigned custom text
- Start to play marker game, a collected marker show's coordinates as 0,0,0 in the KI.
- Link to neighborhood, custom marker text is reset to default and coordinates for all markers are shown as actual coordinates (image 1)
image1
- Link back to Relto, marker game is able to be completed
- Start, stop, reset, edit work properly no matter the location.
- Edited the marker game in the neighborhood, adding custom text to one marker. Upon linking back to Relto, the marker text gets reset.

**MOULa client:**
- Marker game created in Relto, markers given custom text
- Start to play the game, collected markers show coordinates as 0,0,0 in KI
- Link to neighborhood, custom marker text is retained and coordinates for markers are shown as actual coordinates
- Link back to Relto, marker game is able to be completed
- Start, stop, reset, edit work properly no matter the location
- Edited the marker game in the neighborhood, changed custom text on one marker, linked back to Relto, changes are retained.

The main difference between the two clients here is the marker text gets reset when you are playing the game and you link to another age on the H'uru client.

**Comment by DamnBriggsy** [comment]
Python log from when a marker game is stuck in a state where you cannot pick up markers. The last two entries are from where I opened the big KI twice.
[MarkerPython.0.log](https://github.com/H-uru/Plasma/files/10352968/MarkerPython.0.log)

**Comment by DamnBriggsy** [comment]
I can seemingly reproduce the broken marker game state on the MOULa client, but there are no available logs to share. After frantically starting and stopping a marker game, I arrived in a state where I could not pick up any markers. Attempting to stop or reset the game will display --Resetting game-- or --Stopping game-- in the KI until you navigate away. It is not possible to stop or reset a marker game in this state until you log out and log back in again OR link to another age.
MOULaStuckMarkers
The H'uru client will allow you to stop or reset a marker game when it is stuck like this.

**Comment by Hoikas** [comment]
The lost marker text should be fixed now.

**Comment by Hoikas** [comment]
I'm not really sure why the Linux and macOS CIs are failing. IIRC this same code succeeded when I pushed it initially back in July, and it all works on MSVC.

**Comment by dgelessus** [comment]
According to [Clang's very long error](https://github.com/H-uru/Plasma/actions/runs/3869597061/jobs/6595804084#step:6:1977), pyGmMarker's custom overloads of `plPython::ConvertFrom` aren't being found for some reason, so the conversions of the custom enums fail. But I don't have enough deep knowledge of C++ to understand *why* exactly.

**Comment by Hoikas** [comment]
Yeah, that's the way I understand it. I'm not quite sure why the custom enum overloads aren't working... especially when they *were* working previously. 😕

**Comment by DamnBriggsy** [comment]
Another round of testing has confirmed that, after merging these changes, markers and marker games properly retain edited text. Everything seems to be working properly when it comes to marker games, now!

**Comment by Hoikas** [comment]
Rebased to fix merge conflicts.

**Comment by Hoikas** [comment]
This now depends on #1309.

**Review by dpogue — APPROVED** [review]
A few people have tested this and said it works, so we might as well merge it and deal with the consequences later. #yolo

**Pull request merged**
