### PR TITLE
plNetGameLib depends on pnAsyncCoreExe

### PR DESCRIPTION
**Pull request by dpogue**

### CODE REVIEW

**Comment by Hoikas** [comment]
This doesn't seem right... pnAsyncCoreExe is the *private* implementation of pnAsyncCore, so only pnAsyncCore should link against pnAsyncCoreExe. What error are you seeing that makes this change needed?

**Comment by Hoikas** [comment]
Pinging @dpogue for response to earlier question.

**Comment by dpogue** [comment]
I'm getting errors when trying to compile a command-line patcher on Linux, but it's hard to tell which ones are expected because of the missing AsyncSocket stuff and which ones are unexpected because of linking issues. I definitely get fewer errors with this change, but I'm going to mark this as a draft until the socket stuff builds on Linux and I can do more testing.

**Comment by Hoikas** [comment]
Closing per discussion in IRC.

**Comment by dpogue** [comment]
For the sake of documentation, I did figure out what was happening here: pnAsyncCore currently only links with pnAsyncCoreExe on Windows, which results in the undefined references when compiling on Linux.
https://github.com/H-uru/Plasma/blob/88ba573fede78a0c486cea641f7632519c88b724/Sources/Plasma/NucleusLib/pnAsyncCore/CMakeLists.txt#L26

**Pull request closed without merging**
